### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by Kyungchan95** [iotcube/hmark#3]
안녕하세요 hmark를 사용해보았는데 GUI 말고 리눅스 터미널에서 hmark.py 를 실행하는 방법이 있을까요?
터미널에서 실행해도 GUI로 실행돼서요....

**Comment by squizz617** [comment]
안녕하세요. 터미널에서는 아래의 커맨드를 통해 CLI mode로 사용하실 수 있습니다:
```sh
$ cd vuddy/hmark
$ python hmark.py --cli-mode [PATH] [ON/OFF]
```
PATH 에는 타겟 프로그램 소스코드 디렉터리의 경로를 설정하시면 되고, ON/OFF 플래그는 abstraction을 활성화/비활성화 합니다.

사용 예시:
```sh
$ python hmark.py --no-updatecheck --cli-mode ~/personal/albert/src ON                                                                                 1 ↵
Bypassed the update checker.
Running in CLI mode
TARGET: /home/seulbae/personal/albert
ABSTRACTION: ON
PROJ: albert
[+] Loading source files... This may take a few minutes.
[+] Load complete. Generating hashmark...
100.00% src/app/settingswidget/settingswidget.cpp                                                                                                            
[+] Hash index successfully generated.
[+] Saving hash index to file... (Done)

[+] Elapsed time: 5.15 sec.
Program statistics:
 - 24 files;
 - 84 functions;
 - 3633 lines of code.

[+] Hash index saved to: /home/seulbae/workspace/vuddy/hmark/hidx/hashmark_4_albert.hidx
Farewell!

```

아래의 커맨드를 통해 자세한 내용을 확인하실 수 있습니다:
```sh
$ python hmark.py --help
```

**Comment by Kyungchan95** [comment]
빠른 피드백 감사합니다!!

**Comment by Kyungchan95** [comment]
![추가 질문](https://user-images.githubusercontent.com/77317600/107924483-52dedb80-6fb6-11eb-9f2e-6be17b15e979.PNG)

추가적으로 질문이 있습니다. CLI 모드로 실행 후 DB 구축을 하기 위해 DB 생성기 메뉴얼을 보면서 하고 있는데 위 사진처럼 저렇게 오류가 나오는데 어떻게 해결하면 좋을까요?? ㅠㅠ 디렉토리 설정도 다 맞게 하였는데 뭐가 문제인지 모르겠습니다 ㅠ

**Comment by squizz617** [comment]
에러 메시지를 보니 없는 디렉터리에서 linux repo를 찾고 있는 것 같습니다.
`/home/whiteboxDB` 는 프로젝트 기본값인데, `~/VUDDY1/vuddy/vulnDBGen/config.py`를 열어 gitStoragePath를 linux repo를 클론한 디렉터리로 설정하셨는지 다시 한 번 확인 부탁드립니다.

**Comment by Kyungchan95** [comment]
계속 질문드려서 죄송합니다 ㅠㅠ 확인 결과 디렉토리 지정을 잘못 하였었고 그래서 알맞게 설정 후 다시 실행을 하였지만 .... TypeError 문제가 발생하였습니다 ㅠㅠ 이런 상황에선 어떻게 해야 될까요?? 소스 코드 내부의 문제는 없을 거라고 생각하는데 잘 모르겠습니다 ㅠ
![error](https://user-images.githubusercontent.com/77317600/108179946-89992b00-7149-11eb-8154-a60fbedc258f.PNG)

**Comment by squizz617** [comment]
NVD에서 받아오는 데이터베이스의 포맷이 바뀌면서 에러가 발생했습니다.
master 브랜치에 패치를 반영해 놓았으니 `git pull origin master` 하신 뒤에 다시 시도하시면 에러 없이 사용 가능하십니다.
